doctrine_migrations:
    migrations_paths:
        'DoctrineMysqlMigrations': '%kernel.project_dir%/migrations/Mysql'
        'DoctrinePostgresqlMigrations': '%kernel.project_dir%/migrations/Postgresql'
    storage:
        table_storage:
            table_name: doctrine_migration_version
    check_database_platform: true
    enable_profiler: false
    transactional: true
