doctrine:
    dbal:
        dbname: '%env(DB_NAME)%'
        host: '%env(DB_HOST)%'
        port: '%env(DB_PORT)%'
        user: '%env(DB_USER)%'
        password: '%env(DB_PASSWORD)%'
        server_version: '%env(DB_VERSION)%'
        driver: pdo_pgsql
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        filters:
            ownership: App\Doctrine\Filter\OwnershipFilter
            visibility: App\Doctrine\Filter\VisibilityFilter