framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: ~

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'