framework:
    default_locale: '%default_locale%'
    enabled_locales: ['en', 'fr', 'es', 'de', 'it', 'pl', 'pt_BR']
    translator:
        paths:
            - '%kernel.project_dir%/translations/'
        fallbacks:
            - '%default_locale%'
