framework:
    default_locale: '%default_locale%'
    enabled_locales: ['en', 'fr', 'es', 'de']
    translator:
        paths:
            - '%kernel.project_dir%/translations/'
        fallbacks:
            - '%default_locale%'
