files:
  - source: /translations/en/messages.en.xlf
    translation: /translations/%two_letters_code%/messages.%two_letters_code%.%file_extension%
  - source: /translations/en/javascript.en.xlf
    translation: /translations/%two_letters_code%/javascript.%two_letters_code%.%file_extension%
  - source: /translations/*/validators.*.xlf
    translation: /translations/%two_letters_code%/validators.%two_letters_code%.%file_extension%
