_translation_webui:
    resource: '@TranslationBundle/Resources/config/routing_webui.yaml'
    prefix: /admin/translations

_translation_profiler:
    resource: '@TranslationBundle/Resources/config/routing_symfony_profiler.yaml'
