parameters:
    version: 'v1.0.4'
    locale: 'en'
    uuid_regex: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $defaultLocale: '%locale%'
            $showAdminTools: '%env(SHOW_ADMIN_TOOLS)%'
            $version: '%version%'
            $publicPath: '%kernel.project_dir%/public'

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Models,Repository,Tests}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    #Kernel listeners
    App\EventListener\ContextListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 255 }
    App\EventListener\LocaleListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 15 }
            - { name: kernel.event_listener, event: security.interactive_login }
    App\EventListener\FilterListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request}
    App\EventListener\ActivityListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    App\EventListener\NonceListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response }
    App\EventListener\SeenListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response}
    App\EventListener\LogQueueListener:
        tags:
             - { name: kernel.event_listener, event: kernel.response, priority: 5 }

    App\EventListener\AccessDeniedListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    #Global listeners
    App\EventListener\LoggableListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preRemove }
            - { name: doctrine.event_listener, event: onFlush }
    App\EventListener\TimestampableListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
    App\EventListener\OwnershipListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    App\EventListener\ColorListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    #Entity listeners
    App\EventListener\Entity\CollectionListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }
    App\EventListener\Entity\ItemListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }
    App\EventListener\Entity\WishlistListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }
    App\EventListener\Entity\WishListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: onFlush }
    App\EventListener\Entity\MediumListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }
    App\EventListener\Entity\UserListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove }

    #Log
    App\Service\Log\Logger\CollectionLogger:
        tags: [app.logger]
    App\Service\Log\Logger\ItemLogger:
        tags: [app.logger]
    App\Service\Log\Logger\TagLogger:
        tags: [app.logger]
    App\Service\Log\Logger\DatumLogger:
        tags: [app.logger]
    App\Service\Log\LoggerChain:
        arguments: [!tagged app.logger]
