parameters:
    release: '1.4.1'
    default_locale: 'en'
    container.dumper.inline_factories: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $defaultLocale: '%default_locale%'
            $publicPath: '%kernel.project_dir%/public'
            $assetsPath: '%kernel.project_dir%/assets'
            $koillectionRelease: '%release%'
            $kernelProjectDir: '%kernel.project_dir%'
            $env: '%kernel.environment%'

    Api\:
        resource: '../api/*'

    App\:
        resource: '../src/*'
        exclude:
            - '../src/Entity/'
            - '../src/Model/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Api\OpenApi\JwtDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: [ '@.inner' ]

when@test:
    services:
        App\Tests\Factory\:
            resource: '../tests/Factory'