name: Build release image for Docker Hub
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  push_release_image:
    name: Build release image for Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          repository: koillection/koillection-docker
          ref: php8.1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: GITHUB_RELEASE=1.3.15
          tags: docker.io/koillection/koillection:latest,docker.io/koillection/koillection:1.3.15
          platforms: linux/amd64,linux/arm64