name: Build frankenphp image for Docker Hub
on:
  workflow_dispatch:

jobs:
  push_frankenphp_image:
    name: Build frankenphp image for Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          repository: koillection/koillection-docker
          ref: frankenphp
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: GITHUB_RELEASE=frankenphp
          tags: ${{ secrets.REGISTRY_URL }}/koillection/koillection:frankenphp
          platforms: linux/amd64,linux/arm64
