name: Build beta image for Docker Hub
on:
  workflow_dispatch:
  push:
    branches:
      - "test/actions"

jobs:
  push_to_docker_hub:
    name: Build beta image for Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          repository: koillection/koillection-docker
          ref: php8.1
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: GITHUB_RELEASE=master
          tags: docker.io/koillection/koillection:beta
          platforms: linux/amd64,linux/arm64,linux/arm/v7