name: PHPUnit tests with Postgres
on:
  workflow_call:

jobs:
  phpunit:
    name: PHPUnit tests with Postgres ${{ matrix.postgres }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres: [ 10, 11, 12, 13, 14 ]
    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd pg_isready --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v3

      # Setup php env and install dependencies
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring, fileinfo, apcu
      - uses: actions/cache@v3
        id: composer-cache
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # Setup environment variables
      - run: php -r "file_exists('.env.local') || copy('.env', '.env.local');"
      - run: sed -i "s|DB_DRIVER=.*|DB_DRIVER=pdo_pgsql|i" ".env.local"
      - run: sed -i "s|DB_NAME=.*|DB_NAME=koillection|i" ".env.local"
      - run: sed -i "s|DB_HOST=.*|DB_HOST=127.0.0.1|i" ".env.local"
      - run: sed -i "s|DB_PORT=.*|DB_PORT=5432|i" ".env.local"
      - run: sed -i "s|DB_USER=.*|DB_USER=postgres|i" ".env.local"
      - run: sed -i "s|DB_PASSWORD=.*|DB_PASSWORD=root|i" ".env.local"
      - run: sed -i "s|DB_VERSION=.*|DB_VERSION=${{ matrix.mysql }}|i" ".env.local"
      - run: echo "POSTGRES_HOST_AUTH_METHOD=trust" >> ".env.local"

      # Setup yarn
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: (cd assets && yarn install)
      - run: (cd assets && yarn build)

      # Setup test environment
      - run: bin/console lexik:jwt:generate-keypair --env=prod
      - run: bin/console doctrine:database:create --env=prod
      - run: bin/console doctrine:migration:migrate --no-interaction --allow-no-migration --env=prod

      ## Run tests
      - run: php -d memory_limit=512M ./bin/phpunit --stderr